import './globals.css'
import { inter, lineSeedRg, lineSeedBd, lineSeedXBd, lineSeedTh, lineSeedHe } from '@/fonts'

export const metadata = {
  title: 'Kepler portal 🚀',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lineSeedRg.className}>{children}</body>
    </html>
  )
}
